# Q8write about matrix machine learning with its implementation code in 
<H6>In machine learning, matrices are often used to represent datasets and perform operations on 
them. Matrices can represent features, labels, or both in a dataset. They are used in many 
machine learning algorithms, including linear regression, logistic regression, and neural 
networks.</H6>


In [1]:
import numpy as np
# Create a matrix for a dataset
data = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])

In [2]:
data

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
# Create matrices for features and labels
features = np.array([[1, 2],
 [4, 5],
 [7, 8]])
labels = np.array([3, 6, 9])


In [4]:
features

array([[1, 2],
       [4, 5],
       [7, 8]])

In [5]:
labels

array([3, 6, 9])

<h1>We can use these matrices to perform machine learning operations. For example, we can use 
linear regression to predict the label for a new set of features:</h1>

In [7]:
from sklearn.linear_model import LinearRegression
# Create a linear regression model
model = LinearRegression()
# Fit the model to the data
model.fit(features, labels)
# Make a prediction
new_features = np.array([[2, 3],[5, 6]])
predictions = model.predict(new_features)
# Print the predictions
print(predictions)


[4. 7.]
